server:
  port : 8081
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO

spring:
  kafka:
    consumer:
      bootstrap-servers: 130.193.48.189:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ab2-27
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include:
          - health
